# src/WCS/CoavBundle/Resources/config/doctrine/Reservation.orm.yml

WCS\CoavBundle\Entity\Reservation:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\ReservationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        nbSeats:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }

    manyToMany:
        passengers:
            targetEntity: User
            mappedBy: reservation

    manyToOne:
        flight:
            targetEntity: WCS\CoavBundle\Entity\Flight
            inversedBy: flights
            joinColumn:
                name: flight_id
                referencedColumnName: id